spring:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
jpa:
  properties:
    profiles:
      active: local
  open-in-view: false
  logging:
    output:
      ansi:
        enabled: always
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.sql.BasicBinder: TRACE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true